name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Verificar sintaxis
        run: npm run check

      - name: Ejecutar prueba automatizada CP-I01
        run: npm test

      - name: Confirmar pipeline
        run: echo "Pipeline y prueba automatizada ejecutados correctamente"